name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy: 
      matrix:
        php_version: [7.4, 7.3, 7.2, 7.1, 7.0, 5.6]
        wp_version: [latest]
        wp_multisite: [0]
        test: [phpunit]
        include:
          - php_version: 7.4
            wp_multisite: 1
          - php_version: 7.0
            wp_version: 4.9
          - test: phpcs
          - test: coverage
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}
        extensions: mysqli

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php_version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php_version }}-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
      
    - name: Setup WP
      run: script/setup
      env:
        WP_VERSION: ${{ matrix.wp_version }}
        WP_MULTISITE: ${{ matrix.wp_multisite }}
        
    - name: PHPUnit
      if: matrix.test == 'phpunit'
      run: script/cibuild-phpunit
      env:
        WP_MULTISITE: ${{ matrix.wp_multisite }}
    
    - name: phpcs
      if: matrix.test == 'phpcs'
      run: script/cibuild-phpcs
      
    - name: Coverage
      if: matrix.test == 'coverage'
      run: |
        script/cibuild-phpunit-coverage
        script/coveralls




    # - name: Run test suite
    #   run: composer run-script test
