name: On Push

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  WP_POT_Generator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress POT Generator
      uses: varunsridharan/action-wp-pot-generator@2.0
      with:
        save_path: './languages'
        item_slug: 'wp-document-revisions'
        domain: 'wp-document-revisions'
        package_name: 'WP Document Revisions'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}